

package org.lsdt.optaplannerLittleSprouts.solver;
    dialect "java"

import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder;
import org.lsdt.optaplannerLittleSprouts.domain.SchedulingEntity;

global HardSoftScoreHolder scoreHolder;

// ############################################################################
// Hard constraints
// ############################################################################


rule "notEnoughHellos"
    when
        $hello : SchedulingEntity(count < 5, $count : count)
    then
        scoreHolder.addHardConstraintMatch(kcontext, -1);
end

rule "tooManyEnoughHellos"
    when
        $hello : SchedulingEntity(count > 5, $count : count)
    then
        scoreHolder.addHardConstraintMatch(kcontext, -1);
end
